CREATE TABLE IF NOT EXISTS tutor_reports (
  id CHAR(36) NOT NULL PRIMARY KEY,
  reporter_user_id CHAR(36) NOT NULL,
  target_user_id CHAR(36) NOT NULL,
  reported_user_role VARCHAR(20) NOT NULL,
  reported_user_is_parent TINYINT(1) NOT NULL DEFAULT 0,
  source_type ENUM('course_enrollment', 'conversation', 'general') NOT NULL DEFAULT 'general',
  course_id CHAR(36) NULL,
  enrollment_id CHAR(36) NULL,
  conversation_id CHAR(36) NULL,
  reason_category VARCHAR(50) NOT NULL,
  description TEXT NOT NULL,
  status ENUM('pending', 'reviewing', 'resolved', 'dismissed') NOT NULL DEFAULT 'pending',
  action_taken ENUM('none', 'warning_sent', 'account_suspended', 'no_action') NOT NULL DEFAULT 'none',
  admin_notes TEXT NULL,
  reviewed_by CHAR(36) NULL,
  reviewed_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_tutor_reports_status_created (status, created_at),
  KEY idx_tutor_reports_target (target_user_id),
  KEY idx_tutor_reports_reporter (reporter_user_id),
  KEY idx_tutor_reports_course (course_id),
  KEY idx_tutor_reports_conversation (conversation_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
