CREATE TABLE IF NOT EXISTS otp_codes (
  email VARCHAR(255) NOT NULL,
  otp CHAR(64) NOT NULL,
  expires_at DATETIME NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (email)
);

ALTER TABLE otp_codes
  MODIFY COLUMN email VARCHAR(255) NOT NULL,
  MODIFY COLUMN otp CHAR(64) NOT NULL,
  MODIFY COLUMN expires_at DATETIME NOT NULL;
