CREATE TABLE IF NOT EXISTS institution_job_applications (
  id CHAR(36) NOT NULL PRIMARY KEY,
  job_id CHAR(36) NOT NULL,
  institution_id CHAR(36) NOT NULL,
  institution_user_id CHAR(36) NOT NULL,
  tutor_user_id CHAR(36) NOT NULL,
  tutor_profile_id CHAR(36) NOT NULL,
  cover_message TEXT NOT NULL,
  document_url TEXT NULL,
  status ENUM('pending', 'documents_requested', 'approved', 'rejected') NOT NULL DEFAULT 'pending',
  institution_notes TEXT NULL,
  reviewed_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_institution_job_application (job_id, tutor_user_id),
  KEY idx_job_applications_institution_user (institution_user_id, status, created_at),
  KEY idx_job_applications_job (job_id),
  KEY idx_job_applications_tutor (tutor_user_id),
  CONSTRAINT fk_job_applications_job FOREIGN KEY (job_id) REFERENCES institution_jobs(id) ON DELETE CASCADE,
  CONSTRAINT fk_job_applications_institution FOREIGN KEY (institution_id) REFERENCES institution_profiles(id) ON DELETE CASCADE,
  CONSTRAINT fk_job_applications_institution_user FOREIGN KEY (institution_user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_job_applications_tutor_user FOREIGN KEY (tutor_user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_job_applications_tutor_profile FOREIGN KEY (tutor_profile_id) REFERENCES tutor_profiles(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
